development:
  clients:
    default:
      database: etznab_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: etznab_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
